name: 'selestial'

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    network_mode: host

    tty: true
    stdin_open: true

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
